// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXjlPTP13hkdmcQGqYSR4qQqWxyFWtkk',
    appId: '1:564819506011:web:95cb881bb9fcdc6439a07e',
    messagingSenderId: '564819506011',
    projectId: 'easemonie',
    authDomain: 'easemonie.firebaseapp.com',
    storageBucket: 'easemonie.firebasestorage.app',
    measurementId: 'G-BETT10X1CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1_Kfe1D6wRdr4etC93wwx8eqoNhlEDk',
    appId: '1:564819506011:android:89740e0f126e836c39a07e',
    messagingSenderId: '564819506011',
    projectId: 'easemonie',
    storageBucket: 'easemonie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr06cSQ6fc02W4c1Yfp4LbNQ8EZjut020',
    appId: '1:564819506011:ios:b7eb78dbe936c21239a07e',
    messagingSenderId: '564819506011',
    projectId: 'easemonie',
    storageBucket: 'easemonie.firebasestorage.app',
    iosBundleId: 'com.example.esaeMonie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr06cSQ6fc02W4c1Yfp4LbNQ8EZjut020',
    appId: '1:564819506011:ios:b7eb78dbe936c21239a07e',
    messagingSenderId: '564819506011',
    projectId: 'easemonie',
    storageBucket: 'easemonie.firebasestorage.app',
    iosBundleId: 'com.example.esaeMonie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIXjlPTP13hkdmcQGqYSR4qQqWxyFWtkk',
    appId: '1:564819506011:web:7863ad6003256bcb39a07e',
    messagingSenderId: '564819506011',
    projectId: 'easemonie',
    authDomain: 'easemonie.firebaseapp.com',
    storageBucket: 'easemonie.firebasestorage.app',
    measurementId: 'G-20DD84ZM8F',
  );
}
